### ISSUE TITLE
bidirectional LEM

### ISSUE THREAD

**Issue by asmodaay** [tk-rusch/LEM#2]
HI! Great job! Thank you! Do you have any ideas about bidirectional LEM (like lstm)? Can it work and do you wanna code it?

**Comment by tk-rusch** [comment]
Hi, thanks for your interest in our work. Indeed making LEM bidirectional can very easily be done (as it is simply a concatenation of two LEMs -- one forward in time and one backward in time).
As soon as I find some time, I will certainly add this feature to our repository along with a small example.
Just out of curiosity: Did you have a specific application in mind, that requires LEM to be bidirectional?

**Comment by asmodaay** [comment]
I try to compare LEM with LSTM in OCR task. Source model has cnn feature extractor and bidirectional LSTM as sequence decoder. Now I have some difficulties on the training stage (like 95% error rate) and I think if only 1 direction in LEM can be reason for this situation? To reject this hypothesis I start some experiments with 1 direction lstm, will see.

**Comment by rishikksh20** [comment]
@tk-rusch recent DelightfulTTS 2  (https://arxiv.org/abs/2207.04646) using bidirectional LEM for speech synthesis.
I tried to make LEM bidirectional so far not succeeded.

**Comment by rishikksh20** [comment]
@tk-rusch Could you check my code please, in code I am also saving intermediate hidden states :

```python
class BidirectionalSeqLEM(nn.Module):
    def __init__(self, ninp, nhid, nout, dt=1.):
        super(BidirectionalSeqLEM, self).__init__()
        self.nhid = nhid
        self.forward_ = LEMCell(ninp, nhid, dt)
        self.backward_ = LEMCell(ninp, nhid, dt)
        

    def forward(self, input):
      ys = list()
      zs = list()
      ## initialize hidden states
      y = input.data.new(input.size(1), self.nhid).zero_()
      z = input.data.new(input.size(1), self.nhid).zero_()

      y_ = input.data.new(input.size(1), self.nhid).zero_()
      z_ = input.data.new(input.size(1), self.nhid).zero_()

      max_len = input.shape[0]
      for i in range(max_len):
          y, z = self.forward_(input[i, :, :], y, z)
          y_, z_ = self.backward_(input[max_len - i - 1, :, :], y_, z_)
          ys.append(torch.cat([y, y_], dim=-1))
          zs.append(torch.cat([z, z_], dim=-1))
      return torch.stack(ys), torch.stack(zs)
```
